[build]
  command = "hugo --themesDir ../../"
  base    = "choi.netlify.com"
  publish = "choi.netlify.com/public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.57.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"