[build]
  command = "hugo --gc --minify -b $/Users/haeunchoi/HE"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.57.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $/Users/haeunchoi/HE"

[context.branch-deploy]
  command = "hugo --gc --minify -b $/Users/haeunchoi/HE"