

build]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
  command = "hugo --gc --minify -b $URL --themesDir ../../"
  base    = "exampleSite"
  publish = "exampleSite/public"

@@ -10,3 +10,9 @@

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
